rcomp/urls.py
from django.conf.urls import url
from . import views

app_name='rcomp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^result/$', views.result, name='result'),

]

revcomp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('rcomp.urls'))

]

rcomp/models.py
from django.db import models

# Create your models here.

rcomp/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, HTML, Field
from django import forms


class FastaForm(forms.Form):
    seq = forms.CharField(widget=forms.Textarea(attrs={'rows':10, 'cols':100}), label="Fasta sequence", required=False)
    fastafile = forms.FileField(required=False, label="Select Fasta file")

    def __init__(self, *args, **kwargs):
        super(FastaForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-inline'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-2'
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Field('seq', placeholder='''>Example seq
GCAAATGCCGAGTCA'''),
            HTML("<br></br>"),
                'fastafile',
                FormActions(
                        Submit('submit', 'Submit', css_class='btn-primary')))

rcomp/views.py
from __future__ import absolute_import
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .check_sequence import check_sequence, reverse_complement, handle_uploaded_file
import io
from .forms import FastaForm


def home(request):
    return render(request, 'rcomp/home.html')

def index(request):
    if request.method == 'POST':
        form = FastaForm(request.POST, request.FILES)
        if form.is_valid():
            if request.FILES:
                ufile = request.FILES['fastafile']
                content = io.TextIOWrapper(request.FILES['fastafile'].file)
                seq = handle_uploaded_file(ufile, content)
                request.session['val'] = seq
                return HttpResponseRedirect(reverse('rcomp:result'))
            elif request.POST['seq']:
                seq = form.cleaned_data['seq']
                seq = check_sequence(seq)
                request.session['val'] = seq
                return HttpResponseRedirect(reverse('rcomp:result'))
            else:
                return render(request, 'rcomp/index.html', {'form': form})
    else:
        form = FastaForm()
        return render(request, 'rcomp/index.html', {'form': form})


def result(request):
    myval = request.session['val']
    return render(request, 'rcomp/results.html', {'seq': myval})

rcomp/templates/rcomp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Karthik's Tools</title>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
            </head>
            <body>

            <div class="jumbotron text-center">
                  <h1>Bio Toolbelt</h1>
                    <p>A collection of tools written in Django</p>
                </div>
                  
                <div class="container">
                      <div class="row">
                              <div class="col-sm-4">
                                  <h3><a href="{%url 'rcomp:index' %}">Revcomp</h3></a>
                                        <p>Find the reverse complement of any DNA sequence</p>
                                                        </div>
                                                            <div class="col-sm-4">
                                                                      <h3>Coming soon</h3>
                                                                            <p>Stay tuned...</p>
                                                                                      </div>
                                                                                          <div class="col-sm-4">
                                                                                                    <h3>Coming soon</h3>
                                                                                                    <p>Stay tuned..</p>
                                                                                                                    </div>
                                                                                                                      </div>
                                                                                                                  </div>

                                                                                                                  </body>
                                                                                                                  </html>

rcomp/templates/rcomp/index.html
{% load crispy_forms_tags %}
<head xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <meta name="Author" content="Karthik K.N">
    <title> Reverse Complement</title>
</head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">

<div class="jumbotron text-center" style="background-color: #add8d8">
<h2 style="font-family: Merriweather" align="center"> Reverse Complement</h2>
        <p>Convert a DNA sequence into its reverse-complement </p>
    </div>

<p style="font-size: large"> Paste DNA sequence in FASTA format below or upload a fasta file</p>
<br></br>
{% csrf_token %}
{% crispy form %}

rcomp/templates/rcomp/results.html
{% if 'valid' not in seq %}
 <p> Reverse complement of your sequence is:</p> 
{% endif %}
<textarea rows="10" cols="50" readonly>{{ seq }}</textarea>

rcomp/templates/revcomp/index.html
<head xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <meta name="Author" content="Karthik K.N">
    <title> Reverse Complement</title>
</head>
<body text="black", BGCOLOR="teal">
<table CELLPADDING=5 COLS=1 WIDTH="283" BGCOLOR="#ffe4c4" style="margin-left: 45%">
<tr>
<td>
<font color="#8b4513" size=+5>Reverse Complement</font>
</td>
</tr>
</table>
<p><font color="#f0ffff" size=+2 </font>Paste DNA sequence in FASTA format below</p>
<form method="post" action=''>{% csrf_token %}
    <textarea  style="font-size:15px;border: hidden" name="seq" rows="25" cols="100" autofocus="autofocus"
    placeholder=">Example_seq
ttcccatcaagcc"></textarea><br>
    <input type="submit" value="submit" style="width: 5em;height: 2em;" />
</form>

</body>

rcomp/templates/revcomp/results.html
{% if 'valid' not in seq %} <p> Reverse complement of your sequence is:</p> {% endif %}
<pre>{{ seq }}</pre>